version: '3.4'

services:
  category.api:
    image: ${DOCKER_REGISTRY-}code.category.api
    build:
      context: .
      dockerfile: src/Category.Api/Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY-}code.gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile



networks:
  network1:
    driver: bridge
    ipam:
        config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1